### ISSUE TITLE
Cross Compilation

### ISSUE THREAD

**Issue by gmusjha** [ascon/ascon-c#18]
I was trying to follow cross compilation instructions provided in README, i.e

`mkdir build && cd build
cmake .. -DCMAKE_C_COMPILER="arm-linux-gnueabi-gcc" \
         -DREL_FLAGS="-O2;-fomit-frame-pointer;-march=armv7;-mtune=cortex-m4" \
         -DEMULATOR="qemu-arm;-L;/usr/arm-linux-gnueabi" \
         -DALG_LIST="ascon128;ascon128a" -DIMPL_LIST="armv7m;bi32_armv7m"
cmake --build .
ctest`

After cmake once I issue make command, I encountered the following errors:

`make  VERBOSE=1
/usr/bin/cmake -S/opt/ascon/ascon-c -B/opt/ascon/ascon-c/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /opt/ascon/ascon-c/build/CMakeFiles /opt/ascon/ascon-c/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/opt/ascon/ascon-c/build'
make  -f CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/build.make CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/depend
make[2]: Entering directory '/opt/ascon/ascon-c/build'
cd /opt/ascon/ascon-c/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /opt/ascon/ascon-c /opt/ascon/ascon-c /opt/ascon/ascon-c/build /opt/ascon/ascon-c/build /opt/ascon/ascon-c/build/CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/opt/ascon/ascon-c/build'
make  -f CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/build.make CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/build
make[2]: Entering directory '/opt/ascon/ascon-c/build'
[  3%] Building C object CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/crypto_aead/ascon128v12/armv7m/aead.c.o
/usr/bin/arm-linux-gnueabihf-gcc  -I/opt/ascon/ascon-c/crypto_aead/ascon128v12/armv7m -I/opt/ascon/ascon-c/tests -O3 -DNDEBUG -O2 -fomit-frame-pointer -march=armv7 -mtune=cortex-m4 -MD -MT CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/crypto_aead/ascon128v12/armv7m/aead.c.o -MF CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/crypto_aead/ascon128v12/armv7m/aead.c.o.d -o CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/crypto_aead/ascon128v12/armv7m/aead.c.o -c /opt/ascon/ascon-c/crypto_aead/ascon128v12/armv7m/aead.c
cc1: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU
make[2]: *** [CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/build.make:76: CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/crypto_aead/ascon128v12/armv7m/aead.c.o] Error 1
make[2]: Leaving directory '/opt/ascon/ascon-c/build'
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/crypto_aead_ascon128v12_armv7m.dir/all] Error 2
make[1]: Leaving directory '/opt/ascon/ascon-c/build'
make: *** [Makefile:101: all] Error 2`

I assume this error may be due to arm-linux-gnueabihf-gcc compiler, So I copied the files under 

`crypto_aead/ascon80pqv12/armv7m` and they are following ( I added genkat_aead.c from test directory)

`aead.c  architectures  bendian.h  CMakeLists.txt  constants.h    forceinline.h  goal-constbranch  implementors    permutations.h  printstate.h  word.h
api.h   ascon.h        build      config.h        crypto_aead.h  genkat_aead.c  goal-constindex   permutations.c  printstate.c    round.h`

I created a cmake file, and this time I used the arm-linux-gnueabi-gcc compiler. However, It was completed but I got a linker error:

`[ 20%] Building C object CMakeFiles/armFirst.dir/genkat_aead.c.o
/usr/bin/arm-linux-gnueabi-gcc  -I/home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m -fomit-frame-pointer -march=armv7 -mtune=cortex-m4 -MD -MT CMakeFiles/armFirst.dir/genkat_aead.c.o -MF CMakeFiles/armFirst.dir/genkat_aead.c.o.d -o CMakeFiles/armFirst.dir/genkat_aead.c.o -c /home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m/genkat_aead.c
[ 40%] Building C object CMakeFiles/armFirst.dir/aead.c.o
/usr/bin/arm-linux-gnueabi-gcc  -I/home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m -fomit-frame-pointer -march=armv7 -mtune=cortex-m4 -MD -MT CMakeFiles/armFirst.dir/aead.c.o -MF CMakeFiles/armFirst.dir/aead.c.o.d -o CMakeFiles/armFirst.dir/aead.c.o -c /home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m/aead.c
[ 60%] Building C object CMakeFiles/armFirst.dir/permutations.c.o
/usr/bin/arm-linux-gnueabi-gcc  -I/home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m -fomit-frame-pointer -march=armv7 -mtune=cortex-m4 -MD -MT CMakeFiles/armFirst.dir/permutations.c.o -MF CMakeFiles/armFirst.dir/permutations.c.o.d -o CMakeFiles/armFirst.dir/permutations.c.o -c /home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m/permutations.c
[ 80%] Building C object CMakeFiles/armFirst.dir/printstate.c.o
/usr/bin/arm-linux-gnueabi-gcc  -I/home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m -fomit-frame-pointer -march=armv7 -mtune=cortex-m4 -MD -MT CMakeFiles/armFirst.dir/printstate.c.o -MF CMakeFiles/armFirst.dir/printstate.c.o.d -o CMakeFiles/armFirst.dir/printstate.c.o -c /home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m/printstate.c
[100%] Linking C executable armFirst
/usr/bin/cmake -E cmake_link_script CMakeFiles/armFirst.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabi-gcc CMakeFiles/armFirst.dir/genkat_aead.c.o CMakeFiles/armFirst.dir/aead.c.o CMakeFiles/armFirst.dir/permutations.c.o CMakeFiles/armFirst.dir/printstate.c.o -o armFirst  -L/usr/arm-linux-gnueabi 
/usr/lib/gcc-cross/arm-linux-gnueabi/11/../../../../arm-linux-gnueabi/bin/ld: CMakeFiles/armFirst.dir/aead.c.o: in function `ascon_initaead':
aead.c:(.text+0x816): undefined reference to `P8'
/usr/lib/gcc-cross/arm-linux-gnueabi/11/../../../../arm-linux-gnueabi/bin/ld: CMakeFiles/armFirst.dir/aead.c.o: in function `ascon_adata':
aead.c:(.text+0xa80): undefined reference to `P8'
/usr/lib/gcc-cross/arm-linux-gnueabi/11/../../../../arm-linux-gnueabi/bin/ld: aead.c:(.text+0xcbe): undefined reference to `P8'
/usr/lib/gcc-cross/arm-linux-gnueabi/11/../../../../arm-linux-gnueabi/bin/ld: CMakeFiles/armFirst.dir/aead.c.o: in function `ascon_encrypt':
aead.c:(.text+0x1060): undefined reference to `P8'
/usr/lib/gcc-cross/arm-linux-gnueabi/11/../../../../arm-linux-gnueabi/bin/ld: CMakeFiles/armFirst.dir/aead.c.o: in function `ascon_decrypt':
aead.c:(.text+0x1784): undefined reference to `P8'
/usr/lib/gcc-cross/arm-linux-gnueabi/11/../../../../arm-linux-gnueabi/bin/ld: CMakeFiles/armFirst.dir/aead.c.o:aead.c:(.text+0x1cee): more undefined references to `P8' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/armFirst.dir/build.make:145: armFirst] Error 1
make[2]: Leaving directory '/home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m/build'
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/armFirst.dir/all] Error 2
make[1]: Leaving directory '/home/sjha/armsoftwares/ascon/aead/ascon80pqARM7m/build'
make: *** [Makefile:91: all] Error 2
`
I could not understand 

1. linker trying to find P8 which I guess is defined in permuations.h
2. cc1: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU with arm-linux-gnueabihf-gcc
Your help will be appreciated.
Regards,

**Comment by mschlaeffer** [comment]
You could try without the `-mtune=cortex-m4` flag. Another option is a manual build without cmake:
```
arm-linux-gnueabi-gcc -march=armv7 -O2 -Icrypto_aead/ascon128v12/armv7m crypto_aead/ascon128v12/armv7m/*.c -Itests tests/genkat_aead.c -o genkat
qemu-arm -L /usr/arm-linux-gnueabi ./genkat
```

**Comment by mschlaeffer** [comment]
I'm closing this issue. Please reopen if it still persists and my comment did not help.
