### ISSUE TITLE
Padding and little endian: pad byte of 0x80 or 0x01?

### ISSUE THREAD

**Issue by smuellerDD** [ascon/ascon-c#19]
I am implementing the updated Ascon according to SP800-232 in my library leancrypto. As part of the development I found a discrepancy which I would like to check with you:

The patch b12b2a9383e6c changes the following code:

```
-#define PAD(i) SETBYTE(0x80, i)
+#define PAD(i) SETBYTE(0x01, i)
```

May I ask whether this is truly correct? The SP800-232 says:

```
 The function pad(𝑋, 𝑟) appends the bit 1 to the bitstring 𝑋, followed by the
bitstring 0𝑗 ,...
```

So, immediately following the message, the bit 1 is set followed by zeros. Little endian changes the order of *bytes* but not the order of *bits*. Thus, may I ask whether the padding should still be left at 0x80 considering the Ascon implementation operates byte-wise, the addition of the pad-byte is done with a byte-operation (which is unaffected by the little endian notion) and considering that 0x80 in bit-notation is `1000 0000`. 

Think of the message 0x01 0x02 0x03 0x04 0x05 0x06 0x07 - when you load it into a unit64_t variable on little endian and you want to add the padding, you would do:

```
uint64_t a = 0x01020304050607;
uint64_t a_padded = a << 8 | 0x80;
```

a_padded would return 102030405060780 which is seemingly exactly what the specification wants: the first bit in the last byte is set.

When using 0x01 as pad byte, the last bit of the last byte would be set.

**Comment by meichlseder** [comment]
This change is a consequence  of how NIST decided to specify bitstrings and bit indexing for little endian: the bitstring is indexed from LSB to MSB, i.e., appending byte 0x01 appends the abstract bitstring 1,0,0,0,0,0,0,0.
Thus, they do in fact change not only the byte ordering (as expected for little endian), but also the bit indexing (and thus the bit ordering in the abstract bitstring notation used to define the mode).

They give some examples for this in Appendix A (Table 11, print page 34 / pdf page 45) of [NIST SP 800-232](https://doi.org/10.6028/NIST.SP.800-232.ipd).
