### ISSUE TITLE
Public test vectors

### ISSUE THREAD

**Issue by mcraiha** [ascon/ascon-c#4]
Hi,

I don't know to which repo I should post this (so I am sorry if this landed to wrong place)

I am making a C# version of Ascon, but I cannot find any public test vectors for unit testing purposes. I see genkat files, but I would like to have some downloadable text files for this purpose.

Thanks.

**Comment by meichlseder** [comment]
Hi, 

We only have those genkat files as test vectors. You can either run the genkat scripts to produce such text files (they're also included in the repository as plain text files), or download the test vectors directly from the NIST package:
https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/finalist-round/updated-submissions/ascon.zip
Here's an example file for the hash: https://raw.githubusercontent.com/ascon/ascon-c/main/crypto_hash/asconhashv12/LWC_HASH_KAT_256.txt

For a description of what the test vectors cover, see the genkat scripts or NIST's description in their original LWC call.

If you prefer a different format or different set of test vectors, it's probably the easiest to generate them yourself using one of our reference implementations.

Hope this helps.

**Comment by mcraiha** [comment]
Thanks. I finally got matching results today. This issue can now be closed.

For anyone else interested about this:
I used the **LWC_AEAD_KAT_128_128.txt** file and genkat binary compiled with `ASCON_PRINT_STATE` to do the verifications. `crypto_aead_encrypt` doesn't have print for c array after two `STOREBYTES` so you have to do additional checks if you want to trust just the print states. ASCON_PRINT_STATE + genkat produces about 22 megabytes of logs, but first encode + decode part should reveal most of the bugs.

Special thanks for the people that added ASCON_PRINT_STATE, it was very helpful.
