### ISSUE TITLE
aarch64: unknown mnemonic

### ISSUE THREAD

**Issue by cothan** [ascon/ascon-c#6]
Hi, 

I tried to compile this code on ARMv8, Rpi 4. 

```
cothan@raspberrypi:~/work/ascon-c $ lsb_release -a 
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

I only compile the `neon` code portion.
Here is `Makefile`.

```
#/bin/bash

CC = gcc


bench:
	$(CC) -O3 -Icrypto_aead/ascon128v12/neon crypto_aead/ascon128v12/neon/*.c -Itests tests/genkat_aead.c -o genkat
	$(CC) -O3 -Icrypto_aead/ascon128v12/neon crypto_aead/ascon128v12/neon/*.c -DCRYPTO_AEAD -Itests tests/getcycles.c -o getcycles

run:
	./genkat
	./gencycles
```

So I run `make bench`, the compiler output I get: 

```
/tmp/cctBspIk.s:2263: Error: unknown mnemonic `veor' -- `veor q5,q5,q0'
/tmp/cctBspIk.s:2264: Error: unknown mnemonic `veor' -- `veor q6,q6,q1'
/tmp/cctBspIk.s:2265: Error: unknown mnemonic `veor' -- `veor d14,d14,d4'
/tmp/cctBspIk.s:2266: Error: unknown mnemonic `veor' -- `veor q0,q5,q10'
/tmp/cctBspIk.s:2267: Error: unknown mnemonic `veor' -- `veor d4,d14,d24'
/tmp/cctBspIk.s:2268: Error: unknown mnemonic `veor' -- `veor q1,q6,q11'
/tmp/cctBspIk.s:2269: Error: unknown mnemonic `vldr' -- `vldr d31,[x2,#64]'
/tmp/cctBspIk.s:2270: Error: unknown mnemonic `veor' -- `veor d0,d0,d4'
/tmp/cctBspIk.s:2271: Error: unknown mnemonic `veor' -- `veor d4,d4,d3'
/tmp/cctBspIk.s:2272: Error: unknown mnemonic `veor' -- `veor d2,d2,d31'
/tmp/cctBspIk.s:2273: Error: unknown mnemonic `vbic' -- `vbic d13,d0,d4'
/tmp/cctBspIk.s:2274: Error: unknown mnemonic `vbic' -- `vbic d12,d4,d3'
/tmp/cctBspIk.s:2275: Error: unknown mnemonic `veor' -- `veor d2,d2,d1'
/tmp/cctBspIk.s:2276: Error: unknown mnemonic `vbic' -- `vbic d14,d1,d0'
/tmp/cctBspIk.s:2277: Error: unknown mnemonic `vbic' -- `vbic d11,d3,d2'
/tmp/cctBspIk.s:2278: Error: unknown mnemonic `vbic' -- `vbic d10,d2,d1'
/tmp/cctBspIk.s:2279: Error: unknown mnemonic `veor' -- `veor q0,q0,q5'
/tmp/cctBspIk.s:2280: Error: unknown mnemonic `veor' -- `veor q1,q1,q6'
/tmp/cctBspIk.s:2281: Error: unknown mnemonic `veor' -- `veor d4,d4,d14'
/tmp/cctBspIk.s:2282: Error: unknown mnemonic `veor' -- `veor d1,d1,d0'
/tmp/cctBspIk.s:2283: Error: unknown mnemonic `veor' -- `veor d3,d3,d2'
/tmp/cctBspIk.s:2284: Error: unknown mnemonic `veor' -- `veor d0,d0,d4'
/tmp/cctBspIk.s:2285: Error: unknown mnemonic `vsri.64' -- `vsri.64 d14,d4,#7'
/tmp/cctBspIk.s:2286: Error: unknown mnemonic `vsri.64' -- `vsri.64 d24,d4,#41'
/tmp/cctBspIk.s:2287: Error: unknown mnemonic `vsri.64' -- `vsri.64 d11,d1,#39'
/tmp/cctBspIk.s:2288: Error: unknown mnemonic `vsri.64' -- `vsri.64 d21,d1,#61'
/tmp/cctBspIk.s:2289: Error: unknown mnemonic `vsri.64' -- `vsri.64 d10,d0,#19'
/tmp/cctBspIk.s:2290: Error: unknown mnemonic `vsri.64' -- `vsri.64 d20,d0,#28'
/tmp/cctBspIk.s:2291: Error: unknown mnemonic `vsri.64' -- `vsri.64 d12,d2,#1'
/tmp/cctBspIk.s:2292: Error: unknown mnemonic `vsri.64' -- `vsri.64 d22,d2,#6'
/tmp/cctBspIk.s:2293: Error: unknown mnemonic `vsri.64' -- `vsri.64 d13,d3,#10'
/tmp/cctBspIk.s:2294: Error: unknown mnemonic `vsri.64' -- `vsri.64 d23,d3,#17'
/tmp/cctBspIk.s:2295: Error: unknown mnemonic `vsli.64' -- `vsli.64 d10,d0,#45'
/tmp/cctBspIk.s:2296: Error: unknown mnemonic `vsli.64' -- `vsli.64 d20,d0,#36'
/tmp/cctBspIk.s:2297: Error: unknown mnemonic `vsli.64' -- `vsli.64 d11,d1,#25'
/tmp/cctBspIk.s:2298: Error: unknown mnemonic `vsli.64' -- `vsli.64 d21,d1,#3'
/tmp/cctBspIk.s:2299: Error: unknown mnemonic `vsli.64' -- `vsli.64 d12,d2,#63'
/tmp/cctBspIk.s:2300: Error: unknown mnemonic `vsli.64' -- `vsli.64 d22,d2,#58'
/tmp/cctBspIk.s:2301: Error: unknown mnemonic `vsli.64' -- `vsli.64 d13,d3,#54'
/tmp/cctBspIk.s:2302: Error: unknown mnemonic `vsli.64' -- `vsli.64 d23,d3,#47'
/tmp/cctBspIk.s:2303: Error: unknown mnemonic `vsli.64' -- `vsli.64 d14,d4,#57'
/tmp/cctBspIk.s:2304: Error: unknown mnemonic `vsli.64' -- `vsli.64 d24,d4,#23'
```

Those are repeated line from `neon/round.h` function. 
I dig inside and I see it suppose to support `aarch64`, as in `architectures` file: 
```
aarch64
armeabi
arm
```
I tried with both GCC and Clang, same result. 

My GCC: 10.2.1
My Clang: 14.0.6

Let me know if I miss anything.

**Comment by mschlaeffer** [comment]
Looks like the mnemonics have changes for aarch64:
https://developer.arm.com/documentation/den0024/a/AArch64-Floating-point-and-NEON/AArch64-NEON-instruction-format 

Therefore, I think the aarch64 architecture should be removed from this neon implementation version.

Do you think a neon implementation could be faster on aarch64 than the opt64 implementation? The drawback of neon is that implicit rotations are not supported.

**Comment by cothan** [comment]
Hi, 

> Do you think a neon implementation could be faster on aarch64 than the opt64 implementation? The drawback of neon is that implicit rotations are not supported.

That is my investigation right now. I believe the current implementation can be faster, in architecture that support SHA3 instructions (Apple M1), it could be significantly better than `opt64` implementation.

**Comment by mschlaeffer** [comment]
Which specific (new/neon) instructions do you have in mind for Ascon?

**Comment by cothan** [comment]
`bcax, xar` and `sm3, sm4` instructions. Is that ok?

**Comment by mschlaeffer** [comment]
It looks like the instructions are not very general and quite specific to SHA3/SM3. SM3 have hard-coded rotation values but maybe there is still something in it for Ascon.

BCAX and EOR3 look good. XAR (and RAX1) rotate 64-bit words by the same immediate/fixed value, so probably not very useful in Ascon:

XAR:
Rd = (Rn ^ Rm) >>> imm6
R{d+1} = (R{n+1} ^ R{m+1}) >>> imm6

RAX1:
Rd = Rn ^ (Rm <<< 1)
R{d+1} = R{n+1} ^ (R{m+1} <<< 1)

EOR3:
Rd = Rn ^ Rm ^ Ra
R{d+1} = R{n+1} ^ R{m+1} ^ R{a+1}

BCAX:
Rd = Rn ^ (Rm & ~Ra)
R{d+1} = R{n+1} ^ (R{m+1} & ~R{a+1})

The benefit of NEON on 32-bit ARM is the use of 64-bit instructions (and the use of a limited number of 128-bit instructions). Still, porting the NEON implementation to aarch64 and using the new instructions could be worth a try. I did not see dedicated 64-bit instructions but SLI/SRI (shift left/right and insert) could be useful.

**Comment by cothan** [comment]
I agree, another way to implement Ascon in NEON is to use 64-bit vector lane only, 
with NEON instruction, one can use spare vector register to apply `tbl` (Table vector Lookup) instruction, thus the sbox layer will be reduced down to 5 instructions, instead of this part: 

```c
  s->x[0] ^= s->x[4];
  s->x[4] ^= s->x[3];
  s->x[2] ^= s->x[1];
  t.x[0] = s->x[0] ^ (~s->x[1] & s->x[2]); // BCAX can be useful here
  t.x[2] = s->x[2] ^ (~s->x[3] & s->x[4]);
  t.x[4] = s->x[4] ^ (~s->x[0] & s->x[1]);
  t.x[1] = s->x[1] ^ (~s->x[2] & s->x[3]);
  t.x[3] = s->x[3] ^ (~s->x[4] & s->x[0]);
  t.x[1] ^= t.x[0];
  t.x[3] ^= t.x[2];
  t.x[0] ^= t.x[4];
```
become 
```c
t.x[0] = vtbl4_u8(something);
t.x[1] = vtbl4_u8(something);
t.x[2] = vtbl4_u8(something);
t.x[3] = vtbl4_u8(something);
t.x[4] = vtbl4_u8(something);
```
So with table lookup, no need for BCAX which only available in ARMv8.2-sha3. 
Then linear layer can be implemented using SLI, SRI instructions as usual.

**Comment by cothan** [comment]
I see this look up table, if I use 8-bit lookup table to simulate this, will it work? 
I don't mean to look up 64-bit words, just 8 bit. 

![image](https://user-images.githubusercontent.com/9219016/221012903-930d4a80-8f32-4370-a2ee-3689d1fa1c02.png)

**Comment by mschlaeffer** [comment]
The S-box is applied vertically, across words, see the top S-box figure at:
https://ascon.iaik.tugraz.at/specification.html

To use TBL, for the first S-box, bit 0 of each word (register) x0, x1, x2, x3, x4 needs to be moved (transposed) to bits 0,1,2,3,4 of the register where TBL is performed on (this will be the index then). This transposition makes the whole sequence inefficient.

**Comment by cothan** [comment]
You're right. The transposition is inefficient. My last question is, could there be a way to reconstruct a transposed SBOX to use Table lookup efficiently? I don't think so, but I need to ask.

**Comment by mschlaeffer** [comment]
Most likely not efficiently. However, if somebody implements an efficient aarch64 neon implementation, we are happy to take the pull request. Anyway, I'll remove aarch64 for neon, since it does not work on that architecture for now.
