### ISSUE TITLE
ascon-c/tests/demo.c --> mlen variable value

### ISSUE THREAD

**Issue by angel-longueira** [ascon/ascon-c#7]
I am taking a look at the implementation of ASCON in C. I found very useful the "demo.c" program to learn how to use the algorithm. It might be due to my lack of understanding of ASCON, but I realized that "mlen" initial value is 8, instead of 16. The same happens with "alen":

```c
  unsigned char a[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
  unsigned char m[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
  unsigned long long alen = 8;
  unsigned long long mlen = 8;
```

 Is this a typo in the code, or is it just me that I am missing something?

**Comment by mschlaeffer** [comment]
This is just an example, where the data length passed to Ascon is 8 bytes. Not the allocated size. But I agree it's misleading and changed the lengths to 16 bytes.
