### ISSUE TITLE
We are not able to locate the plaintext when running the benchmark

### ISSUE THREAD

**Issue by Ruppity** [ascon/ascon-c#9]
When running the 
```
./getcycles_crypto_aead_ascon128v12_opt32
./getcycles_crypto_aead_ascon128v12_opt32_lowsize
./getcycles_crypto_hash_asconhashv12_opt32
./getcycles_crypto_hash_asconhashv12_opt32_lowsize
```
for the CPU cycle performance I was getting the results and I was looking for what was the input for the plaintext and was not able to find it within the code.

**Comment by mschlaeffer** [comment]
The plaintext is set to some random values. For AEAD it is set in line 76 in `tests/getcycles.c`.

**Comment by Ruppity** [comment]
Thank you so much, @mschlaeffer how can we put a custom plaintext there and run all the benchmarks?

**Comment by mschlaeffer** [comment]
The performance is the same for custom or random plantexts if they have the same length.

To measure the performance of different plaintext (message) lengths, you could add/change the lengths in the `mlens` list and adapt `NUM_MLENS` and `MAX_LEN` accordingly (line 24, 26, 57). Note that the performance is measured for associated data with `alen=0`. A fixed `alen` can be set in line 40.

**Comment by Ruppity** [comment]
Hello again @mschlaeffer once again thank you very much for answering my questions, do you know how to get the cycles in terms of seconds or if there's a calculation to get the sorted cycles in terms of seconds?

**Comment by mschlaeffer** [comment]
A custom plaintext can be set in line 76. `getcycles.c ` does not determine the frequency of the CPU. You'd need to divide manually by the frequency.

**Comment by Ruppity** [comment]
Alright once again thank you very much. I have one more question so what I have to do is divide the Sorted cycles by the frequency right? Do I divide it by the frequency in mHZ or in a different HZ multiple?

**Comment by mschlaeffer** [comment]
By Hz to get the time in seconds. I'm closing the issue since the initial problem is solved.
